version: "3.12"

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5482:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    image: django
    container_name: django_web
    build: .
    restart: on-failure
    tty: true
    command: bash -c "cd /running/delivery && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && cd .."
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/running
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: