# Generated by Django 5.0.6 on 2024-05-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_meow', '0002_user_suc_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
